### ISSUE TITLE
cannot create notebook with whitespaces

### ISSUE THREAD

**Issue by sabinich** [CzBiX/WizNote-to-OneNote#3]
```
Create notebook:
{'error': {'message': 'There is no value specified for the entity name(or displayName in case of Graph endpoint). Name must contain a value and cannot be whitespaces only.', 'code': '20152', '@api.url': 'https://aka.ms/onenote-errors#C20152'}}
```

**Comment by CzBiX** [comment]
You didn't input any name when prompt `Notebook to create(such as WizNote)`
The error message already tell you the reason.

> Name must contain a value and cannot be whitespaces only.

**Comment by sabinich** [comment]
yes, I know it now ;) but when I saw this string "Create notebook", I wrote "import from wiznote".
I think, that better remove this prompt?

**Comment by CzBiX** [comment]
Thanks for your advise, I made some changes to prompt message.
