### ISSUE TITLE
KeyError: 'access_token'

### ISSUE THREAD

**Issue by seancug** [CzBiX/WizNote-to-OneNote#5]
I do exactly as what you said. But it raise a error.
![image](https://user-images.githubusercontent.com/5977375/51014150-1b183500-15a1-11e9-9983-e89893d52c92.png)

**Comment by CzBiX** [comment]
看起来是获取 Token 的时候失败了，我更新了脚本，加上了调试输出。
你重新下载执行看看。

**Comment by seancug** [comment]
好的，谢谢！😁😁😁

**Comment by seancug** [comment]
是我使用的问题, 研究了一下,解决了. 谢谢大神!
