### ISSUE TITLE
Onenote的oauth长度变了

### ISSUE THREAD

**Issue by nov12** [CzBiX/WizNote-to-OneNote#7]
现在url返回的为
`https://login.live.com/oauth20_desktop.srf?code=M.R3_BAY.xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&lc=2052`

所以代码83行已不适用。

PS：我本想改为[\w\\.-]结果出错了，学艺不精的我只好改为了“.”通配。
其他功能一切正常~

**Comment by CzBiX** [comment]
感谢反馈，已修复
